
export interface NewsItem {
  id: string;
  title: string;
  date: string; // ISO or human date (e.g., "2025-07-18" or "July 18, 2025")
  href?: string;
  tag?: string;
  image?: string;    // NEW
  imageAlt?: string; // NEW
}

const news: NewsItem[] = [ 
   {
    id: "118",
    title: "Australia, Pakistan resolve to boost cooperation to curb illegal immigration, ministry says",
    date: "November 29, 2025",
    href: "https://www.arabnews.pk/node/2624300/pakistan",
    tag: "Analysis",
    image: "/Assets/NewsImages/mohsin-naqvi.png",
    imageAlt: "",
   },  
    {
    id: "117",
    title: "Pakistan, Russia Boost Market Ties with CCP-FAS MoU",
    date: "November 29, 2025",
    href: "https://thedailycpec.com/pakistan-russia-boost-market-ties-with-ccp-fas-mou/",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak-russia-boost-market.png",
    imageAlt: "",
   },  
   {
    id: "116",
    title: "High Commissioner of Brunei to Pakistan Receives Global Ambassador Award",
    date: "November 28, 2025",
    href: "https://thediplomaticinsight.com/hc-bunei-receives-global-ambassador-award/#:~:text=Islamabad%20(TDI)%3A%20Kamal%20Bashah,diplomat%20and%20a%20military%20veteran",
    tag: "Analysis",
    image: "/Assets/NewsImages/bunei.webp",
    imageAlt: "",
   },  
  {
    id: "115",
    title: "Pakistan, Malaysia seek deeper maritime cooperation with cadet exchanges, digital trade",
    date: "November 27, 2025",
    href: "https://tribune.com.pk/story/2579166/pakistan-proposes-direct-feeder-lines",
    tag: "Analysis",
    image: "/Assets/NewsImages/feeder-lines.webp",
    imageAlt: "",
   },  
   {
    id: "114",
    title: "Applying for an Australian visa from Pakistan just got easier",
    date: "November 26, 2025",
    href: "https://tribune.com.pk/story/2579083/australia-rolls-out-visa-app-for-pakistani-applicants",
    tag: "Analysis",
    image: "/Assets/NewsImages/aus-visa.webp",
    imageAlt: "",
   },  
   {
    id: "113",
    title: "CM Sindh condemns Indian Defence Minister's provocative statement",
    date: "November 25, 2025",
    href: "https://dunyanews.tv/en/Pakistan/919843-cm-sindh-condemns-indian-defence-ministers-provocative-statement",
    tag: "Analysis",
    image: "/Assets/NewsImages/CM-Sindh.jpg",
    imageAlt: "",
   },  
   {
    id: "112",
    title: "Under CPEC China-Pakistan to Launch Agri Plants",
    date: "November 24, 2025",
    href: "https://thedailycpec.com/under-cpec-china-pakistan-to-launch-agri-plants/",
    tag: "Analysis",
    image: "/Assets/NewsImages/under-CPEC.jpeg",
    imageAlt: "",
   },  
   {
    id: "111",
    title: "Pakistan–ASEAN Trade Reaches USD 11.5bn Despite Deficit. Exports at USD 3.5bn lag behindimports at USD 8bn; Pakistan seeks FTAs/PTAs and SEZ investments.",
    date: "November 23, 2025",
    href: "https://thediplomaticinsight.com/pakistan-asean-trade-climbs-to-11-5bn/#:~:text=Pakistan%20exported%20around%20$3.5%20billion%20worth%20of,of%20Pakistan%27s%20commerce%20with%20the%20regional%20bloc",
    tag: "Analysis",
    image: "/Assets/NewsImages/ASEAN-Pak.webp",
    imageAlt: "",
   },  
   {
    id: "110",
    title: "Punjab CM and Philippine envoy explore investment opportunities. Ambassador Fernandez andCM Maryam Nawaz discussed enhancing economic ties and joint ventures in Punjab.",
    date: "November 22, 2025",
    href: "https://www.brecorder.com/news/40393648",
    tag: "Analysis",
    image: "/Assets/NewsImages/philippness.jpg",
    imageAlt: "",
   },  

    {
    id: "109",
    title: "Pakistan and Australia conclude Bilateral Investment Treaty (BIT) talks with positive progress.",
    date: "November 21, 2025",
    href: "https://www.brecorder.com/news/40393459",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak-aus.jpg",
    imageAlt: "",
   },  
    {
    id: "108",
    title: "Pakistan and Australia move to upgrade their 27-year-old investment accord.",
    date: "November 20, 2025",
    href: "https://24newshd.tv/19-Nov-2025/pakistan-australia-upgrade-investment-accord",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak-aus-investment.jpeg",
    imageAlt: "",
   },  
  {
    id: "107",
    title: "Pakistan vows to enhance multilateral cooperation with China, Russia at SCO moot",
    date: "November 19, 2025",
    href: "https://www.arabnews.com/node/2623143/amp",
    tag: "Analysis",
    image: "/Assets/NewsImages/multilateral.jpg",
    imageAlt: "",
   },  
   {
    id: "106",
    title: "FM Dar arrives in Moscow for Shanghai Cooperation Organisation summit",
    date: "November 18, 2025",
    href: "https://www.dawn.com/news/1955609/dar-to-lead-pakistan-delegation-at-shanghai-cooperation-organisation-summit-in-moscow",
    tag: "Analysis",
    image: "/Assets/NewsImages/dawn-news.jpeg",
    imageAlt: "",
   },  
  
  {
    id: "105",
    title: "Four envoys present diplomatic credentials to Presedent",
    date: "November 18, 2025",
    href: "https://www.brecorder.com/news/40392946/four-envoys-present-diplomatic-credentials-to-president",
    tag: "Analysis",
    image: "/Assets/NewsImages/four-envoys.jpg",
    imageAlt: "",
   },  
   {
    id: "104",
    title: " New China-Pakistan training centre launched ",
    date: "November 17, 2025",
    href: "https://www.nation.com.pk/17-Nov-2025/new-china-pakistan-training-centre-launched",
    tag: "Analysis",
    image: "/Assets/NewsImages/china-pakistan-training.jpeg",
    imageAlt: "",
   },  
   {
    id: "103",
    title: " UMT Marks 76th National Day of China with Seminar",
    date: "November 16, 2025",
    href: "https://academiamag.com/news/umt-marks-76th-national-day-of-china-seminar/",
    tag: "Analysis",
    image: "/Assets/NewsImages/umt.jpeg",
    imageAlt: "",
   },  
    {
    id: "102",
    title: "Pakistan to host prestigious International Space Science Conference",
    date: "November 15, 2025",
    href: "https://www.nation.com.pk/15-Nov-2025/pakistan-host-prestigious-international-space-science-conference",
    tag: "Analysis",
    image: "/Assets/NewsImages/host-spacestation.jpeg",
    imageAlt: "",
   },  
  {
    id: "101",
    title: "CM Maryam Nawaz Sharif Along With Former New Zealand PM Jacinda Ardern Inaugurates Pakistan Pavilion At COP-30 Conference in Brazil",
    date: "November 14, 2025",
    href: "https://dgpr.punjab.gov.pk/node/65649",
    tag: "Analysis",
    image: "/Assets/NewsImages/maryam-nawaz-with-new-zealand.jpeg",
    imageAlt: "",
   },  
   {
    id: "100",
    title: "Signed MoU between Pakistan and Cambodia to establish the Joint Trade Committee ",
    date: "November 14, 2025",
    href: "https://mofa.gov.pk/news/signed-mou-between-pakistan-and-cambodia-to-establish-the-joint-trade-committee?mission=phnom-penh#:~:text=To%20enhance%20trade%20cooperation%20between,signed%20on%2028%20May%202024",
    tag: "Analysis",
    image: "/Assets/NewsImages/pakistan-camoidia.png",
    imageAlt: "",
   },  
   {
    id: "99",
    title: "Punjab CM, Jacinda Ardern inaugurate Pakistan Pavilion at COP30",
    date: "November 13, 2025",
    href: "https://dailytimes.com.pk/1399009/punjab-cm-jacinda-ardern-inaugurate-pakistan-pavilion-at-cop30/",
    tag: "Analysis",
    image: "/Assets/NewsImages/Maryam-1.jpg",
    imageAlt: "",
   },  
   {
    id: "98",
    title: "Pakistan backs China’s bid to host UN tourism regional office",
    date: "November 12, 2025",
    href: "https://www.gwadarpro.pk/1988180184126619649/pakistan-backs-chinas-bid-to-host-un-tourism-regional-office",
    tag: "Analysis",
    image: "/Assets/NewsImages/hostun.png",
    imageAlt: "",
   }, 
  
  {
    id: "97",
    title: "Saudis, Palestinians among delegates arriving in Islamabad for parliamentary speakers’ moot",
    date: "November 11, 2025",
    href: "https://www.arabnews.com/node/2622056/pakistan",
    tag: "Analysis",
    image: "/Assets/NewsImages/saudia.jpg",
    imageAlt: "",
   }, 
  {
    id: "96",
    title: "Pakistan Wins Bid to Host ASOCIO Digital Summit in November 2026",
    date: "November 11, 2025",
    href: "https://propakistani.pk/2025/11/10/pakistan-wins-bid-to-host-asocio-digital-summit-in-november-2026/amp/",
    tag: "Analysis",
    image: "/Assets/NewsImages/proo-pakistani.jpg",
    imageAlt: "",
   }, 
   {
    id: "95",
    title: "Uzbekistan, Pakistan Set to Launch Pilot Cargo Route Through China, Kyrgyzstan ",
    date: "November 11, 2025",
    href: "https://caspianpost.com/economics/uzbekistan-pakistan-set-to-launch-pilot-cargo-route-through-china-kyrgyzstan",
    tag: "Analysis",
    image: "/Assets/NewsImages/uzbekistan2.webp",
    imageAlt: "",
   }, 
  {
    id: "94",
    title: "Delegations arrive in Islamabad ahead of Inter-Parliamentary Speakers’ Conference ",
    date: "November 11, 2025",
    href: "https://www.dawn.com/news/1954130",
    tag: "Analysis",
    image: "/Assets/NewsImages/delegations.jpeg",
    imageAlt: "",
   },
    {
    id: "93",
    title: "Pakistan Eyes New Export Outlets To China, Highlights Success Stories At CIIE",
    date: "November 10, 2025",
    href: "https://www.urdupoint.com/en/world/pakistan-eyes-new-export-outlets-to-china-hi-2080748.html",
    tag: "Analysis",
    image: "/Assets/NewsImages/pakistan-eyes.webp",
    imageAlt: "",
   },
   {
    id: "92",
    title: "Pakistani Entrepreneur selected as Global Youth leader at World Internet Conference",
    date: "November 09, 2025",
    href: "https://www.dailyindependent.com.pk/2025/11/08/pakistani-entrepreneur-selected-as-global-youth-leader-at-world-internet-conference/",
    tag: "Analysis",
    image: "/Assets/NewsImages/enterpreneur.jpg",
    imageAlt: "",
  },
  {
    id: "91",
    title: "Chinese, Pakistani firms ink pact to boost Balochistan’s mining sector ",
    date: "November 08, 2025",
    href: "https://www.nation.com.pk/08-Nov-2025/chinese-pakistani-firms-ink-pact-boost-balochistan-s-mining-sector",
    tag: "Analysis",
    image: "/Assets/NewsImages/Balochistan2.jpeg",
    imageAlt: "",
  },
  {
    id: "90",
    title: "Pakistan committed to expanding defence collaboration with Brunei: CJCSC",
    date: "November 07, 2025",
    href: "https://www.brecorder.com/news/40391204/pakistan-committed-to-expanding-defence-collaboration-with-brunei-cjcsc",
    tag: "Analysis",
    image: "/Assets/NewsImages/sultan.webp",
    imageAlt: "",
  },
    {
    id: "89",
    title: "British army chief meets COAS Munir; both discuss enhancing bilateral defence cooperation",
    date: "November 07, 2025",
    href: "https://www.dawn.com/news/1953492/cjcsc-general-shamshad-expresses-commitment-to-strengthen-defence-cooperation-with-brunei-darussalam",
    tag: "Analysis",
    image: "/Assets/NewsImages/asim-munir.webp",
    imageAlt: "",
  },
    {
    id: "88",
    title: "Pakistan Approves GM Sugarcane and GM Cotton for Commercialization and GM Canola for Food, Feed, and Processing",
    date: "November 06, 2025",
    href: "https://www.isaaa.org/kc/cropbiotechupdate/article/default.asp?ID=21573",
    tag: "Analysis",
    image: "/Assets/NewsImages/biotechbamboo.jpg",
    imageAlt: "",
  },
 {
  
  
    id: "86",
    title: "Japan to dig into Pakistan's Reko Diq mine amid copper deficit fears",
    date: "November 04, 2025",
    href: "https://asia.nikkei.com/business/materials/japan-to-dig-into-pakistan-s-reko-diq-mine-amid-copper-deficit-fears",
    tag: "Analysis",
    image: "/Assets/NewsImages/japan-dig.avif",
    imageAlt: "",
  },
  {
    id: "85",
    title: "Pakistan eyes BRICS+ to boost trade",
    date: "November 02, 2025",
    href: "https://tribune.com.pk/story/2575249/pakistan-eyes-brics-to-boost-trade",
    tag: "Analysis",
    image: "/Assets/NewsImages/eyes.webp",
    imageAlt: "",
  },
  {
    id: "84",
    title: "Pakistan, ASEAN envoys discuss investment cooperation, connectivity and trade facilitation",
    date: "November 01, 2025",
    href: "https://profit.pakistantoday.com.pk/2025/11/01/pakistan-asean-envoys-discuss-investment-cooperation-connectivity-and-trade-facilitation/",
    tag: "Analysis",
    image: "/Assets/NewsImages/profitt.jpeg",
    imageAlt: "",
  },
  {
    id: "83",
    title: "Bilateral trade & economic cooperation: Minister meets ambassadors of Vietnam & Iran",
    date: "October 31, 2025",
    href: "https://www.brecorder.com/news/40390170",
    tag: "Analysis",
    image: "/Assets/NewsImages/trade.jpg",
    imageAlt: "",
  },
  {
    id: "82",
    title: "Tentative dates revealed for Pakistan’s 2026 white-ball tour of Australia.",
    date: "October 29, 2025",
    href: "https://www.cricexec.com/tentative-dates-revealed-for-pakistans-2026-white-ball-tour-of-australia/689563172/",
    tag: "Analysis",
    image: "/Assets/NewsImages/Pakistan’s 2026 white-ball tour of Australia.webp",
    imageAlt: "",
  },
  {
    id: "81",
    title: "Japan honors Pakistani woman for promoting cultural ties. Ms. Neveen Syed received the Japanese Foreign Minister’s Commendation for fostering bilateral cultural exchange.",
    date: "October/www.pk.emb-japan.go.jp/itpr_ja/11_000001_00573.html",
    tag: "Analysis",
    image: "/Assets/NewsImages/Japan honors Pakistani woman.jpg",
    imageAlt: "",
  },
  {
    id: "80",
    title: "Pakistani scholar Areej Sabir wins double honors in China. She earned top awards for research and presentation at the Jiangsu Research Symposium.",
    date: "October 28, 2025",
    href: "https://www.dailyindependent.com.pk/2025/10/27/pakistani-scholar-wins-double-honors-at-chinese-research-symposium/",
    tag: "Analysis",
    image: "/Assets/NewsImages/Pakistani scholar Areej Sabir.jpeg",
    imageAlt: "",
  },
  {
    id: "79",
    title: "Pakistan Embassy in Beijing observes Kashmir Black Day. The event commemorated on October 27, 1947, marking Indian occupation of Jammu and Kashmir.",
    date: "October 28, 2025",
    href: "https://kmsnews.org/kms/2025/10/28/pakistan-embassy-in-beijing-observes-kashmir-black-day.html",
    tag: "Analysis",
    image: "/Assets/NewsImages/Pakistan Embassy in Beijing.png",
    imageAlt: "",
  },
  {
    id: "78",
    title: "Pakistan’s Balakot Hydropower Project Achieves Milestone. The 1,124 MW Balakot project in Khyber Pakhtunkhwa completed river diversion, marking progress on Pakistan’s largest hydropower venture.",
    date: "October 26, 2025",
    href: "https://profit.pakistantoday.com.pk/2025/10/27/balakot-hydropower-project-completes-river-diversion-enters-main-construction-phase/",
    tag: "Analysis",
    image: "/Assets/NewsImages/Balakot Hydropower.jpg",
    imageAlt: "",
  },
  {
    id: "77",
    title: "Pakistan's chemical products see strong growth in Chinese market",
    date: "October 25, 2025",
    href: "https://www.app.com.pk/foreign-correspondent/pakistans-chemical-products-see-strong-growth-in-chinese-market/",
    tag: "Analysis",
    image: "/Assets/NewsImages/pakcheendosti.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "76",
    title: "Pakistan, Australia discuss collaboration to boost meat exports ",
    date: "October 25, 2025 ",
    href: "https://www.nation.com.pk/25-Oct-2025/pakistan-australia-discuss-collaboration-boost-meat-exports",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak-aust.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "75",
    title: "CM felicitates Sanae Takaichi on becoming Japan’s first female PM",
    date: "Oct 23, 2025",
    href: "https://www.app.com.pk/domestic/cm-felicitates-sanae-takaichi-on-becoming-japans-first-female-pm/",
    tag: "Analysis",
    image: "/Assets/NewsImages/japan pm.png",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "74",
    title: "Pakistan eyes global cooperation at international mining conference in Australia today",
    date: "Oct 22, 2025",
    href: "https://www.arabnews.pk/node/2619624/pakistan",
    tag: "Analysis",
    image: "/Assets/NewsImages/mining.jpeg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "73",
    title: "Zardari, Shehbaz felicitate Japan's first female PM",
    date: "Oct 22, 2025",
    href: "https://tribune.com.pk/story/2573565/zardari-shehbaz-felicitate-japans-first-female-pm",
    tag: "Analysis",
    image: "/Assets/NewsImages/shehbaaz.jpeg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "72",
    title: "Dar for deepening ties with EU, Japan",
    date: "Oct 21, 2025",
    href: "https://tribune.com.pk/story/2573368/dar-for-deepening-ties-with-eu-japan",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak-japan.jpeg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "71",
    title: "China–Pakistan Think Tank Dialogue on Modernization and Global Governance Initiative held in Islamabad",
    date: "Oct 20, 2025",
    href: "https://thediplomaticinsight.com/china-pak-think-tank-dialogue-on-modernization-in-islamabad/",
    tag: "Analysis",
    image: "/Assets/NewsImages/china pak.webp",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "70",
    title: "Pakistan, Vietnam set sights on $3b trade goal",
    date: "Oct 18, 2025",
    href: "https://tribune.com.pk/story/2573047/pakistan-vietnam-set-sights-on-3b-trade-goal",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak viet set.webp",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "69",
    title: "Pakistan proposes use of Karachi Port for Bangladesh-China trade",
    date: "Oct 18, 2025",
    href: "https://www.tbsnews.net/bangladesh/pakistan-proposes-use-karachi-port-bangladesh-china-trade-1262761",
    tag: "Analysis",
    image: "/Assets/NewsImages/bang china.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "68",
    title: "Russian envoy meets Tarar to strengthen media partnerships, information exchange",
    date: "Oct 18, 2025",
    href: "https://www.app.com.pk/national/russian-envoy-meets-tarar-to-strengthen-media-partnerships-information-exchange/",
    tag: "Analysis",
    image: "/Assets/NewsImages/russia tarar.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "67",
    title: "ACCWS delegation visits COMSTECH, universities to boost academic, scientific cooperation",
    date: "Oct 19, 2025",
    href: "https://thediplomaticinsight.com/accws-delegation-visits-comstech-universities/",
    tag: "Analysis",
    image: "/Assets/NewsImages/comstech.webp",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "66",
    title: "PM commitment to boost partnership with Australia",
    date: "Oct 16, 2025",
    href: "https://www.brecorder.com/news/40387660/pm-commitment-to-boost-partnership-with-australia",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak aust.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "65",
    title: "Pakistan deepens global partnerships as Japan’s JBIC joins Reko Diq lender group",
    date: "Oct 17, 2025",
    href: "https://www.brecorder.com/news/40387906",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak japan.webp",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "64",
    title: "Russian enovy stresses strengthening people-to-people ties with Pakistan",
    date: "Oct 17, 2025",
    href: "https://www.nation.com.pk/17-Oct-2025/russian-enovy-stresses-strengthening-people-to-people-ties-pakistan",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak russia.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "63",
    title: "Pakistan, Vietnam launch talks on preferential trade agreement to boost economic ties",
    date: "Oct 15, 2025",
    href: "https://www.arabnews.pk/node/2618837/pakistan",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak vietnam trade.png",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "62",
    title: "Pak-Vietnam PTA Talks Scheduled for November.",
    date: "Oct 14, 2025",
    href: "https://vnembassy-islamabad.mofa.gov.vn/en-us/News/EmbassyNews/Pages/Pak-Vietnam-talks-on-PTA-to-be-held-in-November.aspx?p=2",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak vietnam.png",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "61",
    title: "Vietnamese minister arrives in Pakistan",
    date: "Oct 14, 2025",
    href: "https://www.nation.com.pk/14-Oct-2025/vietnamese-minister-arrives-pakistan",
    tag: "Analysis",
    image: "/Assets/NewsImages/vietnamese.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
    {
    id: "60",
    title: "China-Pakistan RMB 5bn water conservancy agreement sets course for smarter, climate-resilient infrastructure",
    date: "Oct 13, 2025",
    href: "http://en.ce.cn/Insight/202510/t20251011_2511597.shtml",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak china water.png",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "59",
    title: "Russia, Pakistan conduct Druzhba 2025 joint military exercises",
    date: "Oct 11, 2025",
    href: "https://www.brecorder.com/news/40387019",
    tag: "Analysis",
    image: "/Assets/NewsImages/pakrussia.webp",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
    {
    id: "58",
    title: "Tim Kane appointed as Australia’s next High Commissioner to Pakistan",
    date: "Oct 11, 2025",
    href: "https://islamabadpost.com.pk/appointed-as-australias-next-high-commissioner-to-pakistan/",
    tag: "Analysis",
    image: "/Assets/NewsImages/tim kane.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
    {
    id: "57",
    title: "Sino-Pak Universities Forge Strategic Partnership for Climate-Resilient Agriculture.",
    date: "Oct 10, 2025",
    href: "https://www.dailyindependent.com.pk/2025/10/09/sino-pak-universities-forge-strategic-partnership-for-climate-resilient-agriculture/",
    tag: "Analysis",
    image: "/Assets/NewsImages/sino-pak.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "56",
    title: "Chinese firm to export mozzarella cheese from Pakistan.",
    date: "Oct 9, 2025",
    href: "https://www.inp.net.pk/news-detail/pak-china/chinese-company-to-export-mozzarella-cheese-from-pakistan",
    tag: "Analysis",
    image: "/Assets/NewsImages/cheese.webp",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
    {
    id: "55",
    title: "Japan provides Rs32m grant assistance to 2 NGOs for development projects in Pakistan.",
    date: "Oct 8, 2025",
    href: "https://www.pk.emb-japan.go.jp/itpr_ja/11_000001_00572.html",
    tag: "Analysis",
    image: "/Assets/NewsImages/japan assistance.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "54",
    title: "Pakistan PM accorded official welcoming ceremony in Malaysia",
    date: "Oct 6, 2025",
    href: "https://asianews.network/pakistan-pm-accorded-official-welcoming-ceremony-in-malaysia/",
    tag: "Analysis",
    image: "/Assets/NewsImages/welcome.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "53",
    title: "PM Shehbaz lands in Kuala Lumpur for three-day Malaysia visit",
    date: "Oct 5, 2025",
    href: "https://www.geo.tv/latest/627032-pm-shehbaz-leaves-for-malaysia-to-deepen-trade-investment-ties",
    tag: "Analysis",
    image: "/Assets/NewsImages/kuala.webp",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
    {
    id: "52",
    title: "Dates Announced for Japanese Language Proficiency Test for Japan Work Visa",
    date: "Oct 4, 2025",
    href: "https://propakistani.pk/2025/10/04/dates-announced-for-japanese-language-proficiency-test-for-japan-work-visa/",
    tag: "Analysis",
    image: "/Assets/NewsImages/japanese test.avif",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "51",
    title: "Pakistan Expresses Solidarity with Philippines, Indonesia Following Devastating Earthquakes",
    date: "Oct 3, 2025",
    href: "https://thediplomaticinsight.com/pak-expresses-solidarity-with-indonesia-philippines-after-quakes/",
    tag: "Analysis",
    image: "/Assets/NewsImages/phillipines.webp",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "50",
    title: "Pakistan outplays New Zealand in ATF 12 & under championships",
    date: "Oct 3, 2025",
    href: "https://tribune.com.pk/story/2570126/pakistan-outplays-new-zealand-in-atf-12-under-championships",
    tag: "Analysis",
    image: "/Assets/NewsImages/atf.webp",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "49",
    title: "Pakistani, Malaysian leaders discuss Trump's Gaza ceasefire plan, counterterrorism",
    date: "Oct 7, 2025",
    href: "https://www.aa.com.tr/en/asia-pacific/pakistani-malaysian-leaders-discuss-trumps-gaza-ceasefire-plan-counterterrorism-/3708524",
    tag: "Analysis",
    image: "/Assets/NewsImages/gaza ceasefire.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "48",
    title: "Malaysia, Pakistan to deepen cooperation in defence, aviation, healthcare and cybersecurity",
    date: "Oct 7, 2025",
    href: "https://www.malaymail.com/news/malaysia/2025/10/06/malaysia-pakistan-to-deepen-cooperation-in-defence-aviation-healthcare-and-cybersecurity/193641",
    tag: "Analysis",
    image: "/Assets/NewsImages/malay and pak.png",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "47",
    title: "Pakistan explores mining opportunities with Australia, Finland",
    date: "Oct 2, 2025",
    href: "https://profit.pakistantoday.com.pk/2025/10/01/pakistan-explores-mining-opportunities-with-australia-finland/",
    tag: "Analysis",
    image: "/Assets/NewsImages/mining.png",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "46",
    title: "Pakistan proposes China-Gwadar-Africa logistics corridor to boost maritime trade",
    date: "Oct 2, 2025",
    href: "https://www.arabnews.pk/node/2614170/pakistan",
    tag: "Analysis",
    image: "/Assets/NewsImages/gwadar.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "45",
    title: "Ahsan seeks 10,000 PhD scholarships for Pakistani students, ASEAN-level trade access under CPEC 2.0",
    date: "Sep 29, 2025",
    href: "https://www.app.com.pk/business/ahsan-seeks-10000-phd-scholarships-for-pakistani-students-asean-level-trade-access-under-cpec-2-0/",
    tag: "Analysis",
    image: "/Assets/NewsImages/ahsan.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "44",
    title: "OEC starts Japanese language course for skilled workers",
    date: "Sep 29, 2025",
    href: "https://www.nation.com.pk/29-Sep-2025/oec-starts-japanese-language-course-skilled-workers",
    tag: "Analysis",
    image: "/Assets/NewsImages/OEC.webp",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "43",
    title: "Australian High Commissioner pays farewell call on Azam Nazeer Tarar",
    date: "Sep 27, 2025",
    href: "https://www.app.com.pk/national/australian-high-commissioner-pays-farewell-call-on-azam-nazeer-tarar/",
    tag: "Analysis",
    image: "/Assets/NewsImages/azam nazeer.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "42",
    title: "Japan’s Terra Motors Enters Pakistan with Electric Three-Wheeler ‘Kyoro’",
    date: "Sep 25, 2025",
    href: "https://imrozepakistan.com/japans-terra-motors-enters-pakistan-with-electric-three-wheeler-kyoro/",
    tag: "Analysis",
    image: "/Assets/NewsImages/terra-motors.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "41",
    title: "Pakistan-Vietnam to sign PTA soon",
    date: "Sep 25, 2025",
    href: "https://moderndiplomacy.eu/2025/09/25/pakistan-vietnam-to-sign-pta-soon/",
    tag: "Analysis",
    image: "/Assets/NewsImages/vietnam-trade.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "40",
    title: "Japan shows interest in investing in Pakistan’s Reko Diq copper and gold mining project.",
    date: "Sep 24, 2025",
    href: "https://tribune.com.pk/story/2568600/japan-intends-to-invest-in-reko-diq-project",
    tag: "Analysis",
    image: "/Assets/NewsImages/japan investment.webp",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "39",
    title: "Pakistan delegation represents country at APPCED moot in Seoul, led by Senator Pervaiz Rashid.",
    date: "Sep 24, 2025",
    href: "https://www.nation.com.pk/24-Sep-2025/pak-delegation-represents-country-parliamentarians-moot-seoul",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak-delegation.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "38",
    title: "China to supply high-speed train units for Islamabad-Rawalpindi service launching in March 2026",
    date: "Sep 23, 2025",
    href: "https://propakistani.pk/2025/09/23/china-to-provide-high-speed-train-units-to-pakistan/#:~:text=Special%20train%20units%20will%20be,operations%20on%20March%2023%2C%202026",
    tag: "Analysis",
    image: "/Assets/NewsImages/bullet train.avif",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "37",
    title: "Pakistani scientist in China awarded Tamgha-e-Imtiaz for agricultural innovation",
    date: "Sep 23, 2025",
    href: "http://en.ce.cn/Insight/202509/t20250922_2483411.shtml",
    tag: "Analysis",
    image: "/Assets/NewsImages/tamgha e imtiaz.png",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "36",
    title: "Gilani calls for enhancing of trade, climate cooperation with Australia",
    date: "Sep 23, 2025",
    href: "https://dailytimes.com.pk/1372527/gilani-calls-for-enhancing-of-trade-climate-cooperation-with-australia/",
    tag: "Analysis",
    image: "/Assets/NewsImages/gillani.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "35",
    title: "Vietnam, Pakistan deepen ties with new honorary consulate in Lahore",
    date: "Sep 23, 2025",
    href: "https://english.vov.vn/en/politics/vietnam-pakistan-deepen-ties-with-new-honorary-consulate-in-lahore-post1232021.vov",
    tag: "Analysis",
    image: "/Assets/NewsImages/pakistan vietnam.webp",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
 {
    id: "34",
    title: "Pakistan, China Mark 76th Anniversary With Stronger Ties",
    date: "Sep 23, 2025",
    href: "https://thedailycpec.com/pakistan-china-mark-76th-anniversary-with-stronger-ties/",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak china 76th.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  //Pak related news above
  {
    id: "33",
    title: "Pakistan, China seal $601m agriculture JVs",
    date: "Sep 11, 2025",
    href: "https://tribune.com.pk/story/2566147/pakistan-china-seal-601m-agriculture-jvs",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak china handshake.webp",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "32",
    title: "Australia names streets after Pakistani cities.",
    date: "Aug 7, 2025",
    href: "https://arynews.tv/australia-now-has-its-own-karachi-multan-and-quetta",
    tag: "Analysis",
    image: "/Assets/NewsImages/City.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "31",
    title: "Pakistan, Japan renew bilateral cooperation",
    date: "Sep 23, 2025",
    href: "https://www.app.com.pk/business/pakistan-japan-renew-resolve-to-enhance-bilateral-cooperation/",
    tag: "Analysis",
    image: "/Assets/NewsImages/pakistan-and-japan.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "30",
    title: "Pakistan to issue $1bn Panda bonds in Chinese capital market by December",
    date: "Sep 11, 2025",
    href: "https://www.samaa.tv/2087339088-pakistan-to-issue-1bn-in-panda-bonds-through-chinese-capital-market",
    tag: "Analysis",
    image: "/Assets/NewsImages/panda-bond.webp",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "29",
    title: "China to work with Pakistan to implement outcome of Tianjin Summit: Envoy.",
    date: "Sep 11, 2025",
    href: "https://www.nation.com.pk/11-Sep-2025/china-to-work-with-pakistan-to-implement-outcome-of-tianjin-summit-envoy",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak china.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "28",
    title: "Pakistan's president to visit China today in efforts to boost economic and trade cooperation.",
    date: "Sep 12, 2025",
    href: "https://www.arabnews.com/node/2615003/pakistan",
    tag: "Analysis",
    image: "/Assets/NewsImages/visit to china.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "27",
    title: "China to Train Pakistani Engineers. ",
    date: "Sep 12, 2025",
    href: "https://propakistani.pk/2025/09/12/china-to-train-pakistani-engineers/#:~:text=Pakistan%20Engineering%20Council%20(PEC)%20has,Pakistani%20engineers%2C%20and%20Chinese%20language",
    tag: "Analysis",
    image: "/Assets/NewsImages/pak china.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "26",
    title: "PU and Chinese varsity collaborate on crop varieties, food security.",
    date: "Sep 13, 2025",
    href: "https://fees.pu.edu.pk/home/section/exam/16420",
    tag: "Analysis",
    image: "/Assets/NewsImages/crop varieties.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "25",
    title: "Pak Ambassador inaugurates Digital Pakistan Pavilion at CIFTIS.",
    date: "Sep 15, 2025",
    href: "https://www.nation.com.pk/15-Sep-2025/pak-ambassador-inaugurates-digital-pakistan-pavilion-at-ciftis-2025",
    tag: "Analysis",
    image: "/Assets/NewsImages/summit.jpeg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "24",
    title: "Pakistani nursing students to get 25 scholarships in China.",
    date: "Sep 15, 2025",
    href: "https://www.nation.com.pk/15-Sep-2025/pakistani-nursing-students-to-receive-25-scholarships-in-china#:~:text=ISLAMABAD%20%2D%20The%20China%2DPakistan%20TVET,scholarships%20for%20Pakistani%20nursing%20students",
    tag: "Analysis",
    image: "/Assets/NewsImages/nursing scholarship.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
   {
    id: "23",
    title: "Pakistan-China collaboration in defence, aviation to expand",
    date: "Sep 14, 2025",
    href: "https://tribune.com.pk/story/2566801/pakistan-china-collaboration-in-defence-aviation-to-expand-president-zardari",
    tag: "Analysis",
    image: "/Assets/NewsImages/Pakistan china collaboration.webp",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },
  {
    id: "1",
    title: "Pakistan and China agreed to boost agricultural cooperation.",
    date: "July 18, 2025",
    href: "https://thedailycpec.com/pakistan-invites-chinese-firms-to-invest-in-agri-sector/",
    tag: "Analysis",
    image: "/Assets/NewsImages/1.jpg",
    imageAlt: "IMG_Pakistan and China agriculture cooperation",
  },
  {
    id: "2",
    title: "The first batch of 300 Pakistani graduates completed advanced agriculture training in China.",
    date: "August 15, 2025",
    href: "https://www.arabnews.com/node/2608529/pakistan",
    tag: "Analysis",
    image: "/Assets/NewsImages/2.jpg",
    imageAlt: "IMG_The first batch of 300 Pakistani graduates completed advanced agriculture training in China.",
  },
  {
    id: "3",
    title: "Pakistan, South Korea explore tech and digital cooperation. ",
    date: "August 15, 2025",
    href: "https://www.app.com.pk/national/pakistan-korea-discuss-enhanced-cooperation-in-technology-skills-development/",
    tag: "Analysis",
    image: "/Assets/NewsImages/3.jpg",
    imageAlt: "IMG_Pakistan, South Korea explore tech and digital cooperation.",
  },
  {
    id: "4",
    title: "Vietnam proposes deepening cultural ties with Pakistan, focus on Buddhist Heritage.",
    date: "July 18, 2025",
    href: "https://www.app.com.pk/national/vietnam-proposes-cultural-collaboration-with-pakistan-to-promote-buddhist-heritage/#:~:text=The%20significance%20of%20this%20partnership,Buddhist%20heritage%20from%20various%20dynasties.",
    tag: "Analysis",
    image: "/Assets/NewsImages/4.jpeg",
    imageAlt: "IMG_Vietnam proposes deepening cultural ties with Pakistan, focus on Buddhist Heritage.",
  },
  {
    id: "5",
    title: "China ready to build upgraded version of CPEC, Xi tells Shehbaz",
    date: "Sep 03, 2025",
    href: "https://www.nation.com.pk/03-Sep-2025/china-ready-to-build-upgraded-version-of-cpec-xi-tells-shehbaz",
    tag: "Analysis",
    image: "/Assets/NewsImages/china-pak.jpg",
    imageAlt: "IMG_China ready to build upgraded version of CPEC, Xi tells Shehbaz",
  },
    {
    id: "6",
    title: "SK Hydropower Station showcased at SCO Summit 2025 as model of China-Pakistan Cooperation",
    date: "Sep 03, 2025",
    href: "https://www.app.com.pk/national/sk-hydropower-station-showcased-at-sco-summit-2025-as-model-of-china-pakistan-cooperation/",
    tag: "Analysis",
    image: "/Assets/NewsImages/hydropower.jpg",
    imageAlt: "IMG_SK Hydropower Station showcased at SCO Summit 2025 as model of China-Pakistan Cooperation",
  },
   {
    id: "7",
    title: "Honorary Japan CG calls on Governor Balochistan.",
    date: "Sep 02, 2025",
    href: "https://www.dailyindependent.com.pk/2025/09/02/honorary-japan-cg-calls-on-governor-balochistan/",
    tag: "Analysis",
    image: "/Assets/NewsImages/honory.jpg",
    imageAlt: "IMG_Honorary Japan CG calls on Governor Balochistan.",
  },
  {
    id: "8",
    title: "PM raises Indus Waters Treaty issue at SCO",
    date: "Sep 03, 2025",
    href: "https://tribune.com.pk/story/2564580/pm-raises-indus-waters-treaty-issue-at-sco",
    tag: "Analysis",
    image: "/Assets/NewsImages/pm.jpg",
    imageAlt: "IMG_PM raises Indus Waters Treaty issue at SCO",
  },
  
  {
    id: "9",
    title: "Pakistan’s FCCI business delegation visits Expo 2025 Osaka",
    date: "Sep 1, 2025",
    href: "https://www.brecorder.com/news/40380603/pakistans-fcci-business-delegation-visits-expo-2025-osaka",
    tag: "Analysis",
    image: "/Assets/NewsImages/osaka.jpg",
    imageAlt: "IMG_Pakistan’s FCCI business delegation visits Expo 2025 Osaka",
  },
  {
    id: "10",
    title: "Pakistani-origin MP Bisma Asif denounces reclaim Australia rally",
    date: "Aug 31, 2025",
    href: "https://www.theaustraliatoday.com.au/speaking-urdu-in-queensland-parliament-pakistani-origin-mp-bisma-asif-denounces-reclaim-australia-rally/",
    tag: "Analysis",
    image: "/Assets/NewsImages/bisma_asif.jpg",
    imageAlt: "IMG_Pakistani-origin MP Bisma Asif denounces reclaim Australia rally",
  },
  
{
    id: "11",
    title: "Alibaba strengthens presence in Pakistan.",
    date: "Aug 28, 2025",
    href: "https://www.app.com.pk/foreign-correspondent/alibaba-strengthens-its-presence-in-pakistans-digital-economy/#:~:text=BEIJING%2C%20Aug.,support%20local%20businesses%20and%20consumers.",
    tag: "Analysis",
    image: "/Assets/NewsImages/alibaba.jpg",
    imageAlt: "IMG_Alibaba strengthens presence in Pakistan.",
  },
  {
    id: "12",
    title: "Pakistan welcomes Japan Bank’s interest in Reqo Diq project",
    date: "Sep 1, 2025",
    href: "https://www.brecorder.com/news/40380163/pakistan-welcomes-japan-banks-interest-in-reqo-diq-project;",
    tag: "Analysis",
    image: "/Assets/NewsImages/raqodiq.jpg",
    imageAlt: "IMG_Pakistan welcomes Japan Bank’s interest in Reqo Diq project",
  },
  {
    id: "13",
    title: "Australia Announces New High Commissioner To Pakistan",
    date: "Aug 31, 2025",
    href: "https://www.nationaltribune.com.au/australia-announces-new-high-commissioner-to-pakistan-31-august/",
    tag: "Analysis",
    image: "/Assets/NewsImages/Australia High Comission.jpg",
    imageAlt: "IMG_Australia Announces New High Commissioner To Pakistan",
  },
  {
    id: "14",
    title: "Pakistan committed to deepen economic ties with Malaysia",
    date: "Aug 31, 2025",
    href: "https://www.nation.com.pk/31-Aug-2025/pakistan-committed-to-deepen-economic-ties-with-malaysia",
    tag: "Analysis",
    image: "/Assets/NewsImages/Pak_Malay.jpg",
    imageAlt: "IMG_Pakistan committed to deepen economic ties with Malaysia",
  },
  {
    id: "15",
    title: "PM Shehbaz invites Chinese businesses to invest in Pakistan",
    date: "Sep 03, 2025",
    href: "https://tribune.com.pk/story/2564871/pm-shehbaz-invites-chinese-businesses-to-invest-in-pakistan;",
    tag: "Analysis",
    image: "/Assets/NewsImages/PM Shehbaz.jpg",
    imageAlt: "IMG_PM Shehbaz invites Chinese businesses to invest in Pakistan",
  },
  {
    id: "16",
    title: "Pakistan, China to ink 11 training accords under CPEC phase-II",
    date: "Sep 10, 2025",
    href: "https://profit.pakistantoday.com.pk/2025/09/03/pakistan-china-to-ink-11-training-accords-under-cpec-phase-ii/;",
    tag: "Analysis",
    image: "/Assets/NewsImages/CPEC.jpg",
    imageAlt: "IMG_Pakistan, China to ink 11 training accords under CPEC phase-II",
  },
  {
    id: "17",
    title: "Pakistan enjoys preferred place in US new South Asia approach",
    date: "Sep 04, 2025",
    href: "https://tribune.com.pk/story/2565061/pakistan-enjoys-preferred-place-in-us-new-south-asia-approach-report;",
    tag: "Analysis",
    image: "/Assets/NewsImages/Pakistan enjoys.jpg",
    imageAlt: "IMG_Pakistan enjoys preferred place in US new South Asia approach",
  },
  {
    id: "18",
    title: "Malaysian Food Festival opens in Islamabad",
    date: "Sep 04, 2025",
    href: "https://www.app.com.pk/business/malaysian-food-festival-opens-in-islamabad/",
    tag: "Analysis",
    image: "/Assets/NewsImages/Malaysian Food Festival.jpg",
    imageAlt: "IMG_Malaysian Food Festival opens in Islamabad",
  },
  {
    id: "19",
    title: "Pakistan, China sign $8.5b pacts under CPEC 2.0",
    date: "Sep 5, 2025",
    href: "https://www.nation.com.pk/05-Sep-2025/pakistan-china-sign-dollar-8-5b-pacts-under-cpec-2-0",
    tag: "Analysis",
    image: "/Assets/NewsImages/Pakistan, China sign $8.5b.jpg",
    imageAlt: "IMG_Pakistan, China sign $8.5b pacts under CPEC 2.0",
  },
  {
    id: "20",
    title: "Pakistan and Japan hold 14th round of bilateral political consultations",
    date: "Sep 04, 2025",
    href: "https://ptv.com.pk/ptvworld/newsdetail/11152",
    tag: "Analysis",
    image: "/Assets/NewsImages/Pakistan and Japan hold 14th.jpg",
    imageAlt: "IMG_Pakistan and Japan hold 14th round of bilateral political consultations",
  },
 
  {
    id: "21",
    title: "Pakistan, China sign $4bn MoUs in agriculture",
    date: "Sep 04, 2025",
    href: "https://www.dawn.com/news/1940384/pakistan-china-sign-4bn-mous-in-agriculture",
    tag: "Analysis",
    image: "/Assets/NewsImages/Pakistan, China sign $4bn.jpg",
    imageAlt: "IMG_Pakistan, China sign $4bn MoUs in agriculture",
  },
  {
    id: "22",
    title: "Pakistan, China agree on $7bn ML-1 financing consortium",
    date: "Sep 08, 2025",
    href: "https://www.dawn.com/news/1940653",
    tag: "Analysis",
    image: "/Assets/NewsImages/Pakistan, China agree on $7bn.jpg",
    imageAlt: "IMG_Pakistan, China agree on $7bn ML-1 financing consortium",
  },

];

export function getNews(): NewsItem[] {
  return news;
}

export function getRecentNews(limit?: number): NewsItem[] {
  const monthToIndex: Record<string, number> = {
    january: 0,
    february: 1,
    march: 2,
    april: 3,
    may: 4,
    june: 5,
    july: 6,
    august: 7,
    september: 8,
    october: 9,
    november: 10,
    december: 11,
  };

  function parseNewsDate(dateString: string): number {
    // ISO YYYY-MM-DD
    const iso = /^(\d{4})-(\d{2})-(\d{2})$/;
    const isoMatch = dateString.match(iso);
    if (isoMatch) {
      const year = Number(isoMatch[1]);
      const month = Number(isoMatch[2]) - 1;
      const day = Number(isoMatch[3]);
      return Date.UTC(year, month, day);
    }

    // Month DD, YYYY (English)
    const long = /^(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2}),\s*(\d{4})$/i;
    const longMatch = dateString.match(long);
    if (longMatch) {
      const monthName = longMatch[1].toLowerCase();
      const day = Number(longMatch[2]);
      const year = Number(longMatch[3]);
      const monthIndex = monthToIndex[monthName];
      if (monthIndex >= 0) return Date.UTC(year, monthIndex, day);
    }

    // Fallback: native parser
    const t = Date.parse(dateString);
    return Number.isFinite(t) ? t : 0;
  }

  const arr = [...news].sort((a, b) => parseNewsDate(b.date) - parseNewsDate(a.date));
  return typeof limit === "number" ? arr.slice(0, limit) : arr;
}
